#!/bin/bash
# This script shows all the files that need farmer_id parseInt fix

echo "Files with farmer_id issue:"
echo "============================"
echo ""
echo "ISFS_backend/routes/viewsRoutes.js - 5 locations"
echo "ISFS_backend/routes/weatherRoutes.js - 7 locations"
echo "ISFS_backend/routes/proceduresRoutes.js - 2 locations"
echo "ISFS_backend/routes/salesRoutes.js - 3 locations"
echo "ISFS_backend/routes/labourRoutes.js - 1 location"
echo "ISFS_backend/routes/labourWorkRoutes.js - 2 locations"
echo "ISFS_backend/routes/notificationRoutes.js - ? locations"
echo "ISFS_backend/routes/fertilizerRoutes.js - 2 locations"
echo "ISFS_backend/routes/functionsRoutes.js - 1 location"
echo "ISFS_backend/routes/cropRoutes.js - 5 locations"
echo "ISFS_backend/routes/equipmentRoutes.js - 3 locations"
echo "ISFS_backend/routes/analyticsRoutes.js - 2 locations"
echo ""
echo "Total: ~33 locations across 13 files"
echo ""
echo "All need to change:"
echo "  FROM: const farmer_id = req.farmer?.farmer_id;"
echo "  TO:   const farmer_id = parseInt(req.farmer?.farmer_id);"

